node {
    def mvnHome = tool 'M3'

    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        sh "echo Build is passed"
    }

    stage('Build') {
        sh "${mvnHome}/bin/mvn -v"
    }
}
